# Generated by Django 4.1 on 2022-08-17 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custmuser',
            old_name='telefono',
            new_name='number',
        ),
    ]
